# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build
on:
  workflow_dispatch:
  push:

jobs:
  build:
    name: More checks

    runs-on: [self-hosted, linux]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
